### ISSUE TITLE
Support for 5.3?

### ISSUE THREAD

**Issue by N02SRT** [tomcorbett/opentok-laravel#10]
Hello, I am trying to update to laravel 5.3 and this package is holding me back from doing so. Can you update your composer.json file for 5.3 and update "opentok/opentok": "dev-hitlabs" to "opentok/opentok": "2.4.x". Thanks!

**Comment by tomcorbett** [comment]
Hi @N02SRT - please feel free to send me a PR with these changes if you can and I will cut a new release with this.

**Comment by tomcorbett** [comment]
closing doing on #11
