### ISSUE TITLE
I can't install

### ISSUE THREAD

**Issue by ReyesMagos** [tomcorbett/opentok-laravel#2]
Hello. I can't install opentok-laravel. Prompt this:

![image](https://cloud.githubusercontent.com/assets/6519687/3759729/d1d90240-1864-11e4-8652-2de55dafa694.png)

I have installed opentok/opentok correctly in the vendors folder. 

Any solution?

Thanx

**Comment by tomcorbett** [comment]
closing as I don't think this is a problem anymore
