### ISSUE TITLE
What about Laravel 5 support?

### ISSUE THREAD

**Issue by simplenotezy** [tomcorbett/opentok-laravel#5]

**Comment by tomcorbett** [comment]
Hi @canfiax I am not using laravel 5 yet and am not currently actively using laravel either, as I am very busy on other projects at the moment, but if you want to put in a pull request for the necessary changes, please feel free. Apologies for this!

**Comment by namelivia** [comment]
Hey, I've forked this repository and modified it for Laravel 5+ (it's currently successfully implemented in one of our 5.2 projects). I don't exactly know about the retrocompatibility of this but I think it is not retrocompatible so I don't know if merging a PR would break things for some other people projects.

**Comment by tomcorbett** [comment]
Hi @namelivia thank you very much for that! I am fine with merging in and just tagging a new release 1.1.0 or something like that and I or you can update the readme to let people know which version to use for which versions of Laravel?

**Comment by namelivia** [comment]
Ok, I'll be cleaning up things a bit and make a PR. Thanks!

**Comment by tomcorbett** [comment]
@namelivia awesome thank you!

**Comment by zedee** [comment]
Seems that I did the same some days ago with this repo! But I think @namelivia version is better adapted.

**Comment by namelivia** [comment]
I have created a pull request, I was updating the documentation and rebasing so guys can go ther and take a look to see if something looks weird to you or could be improved. Thanks!
