### ISSUE TITLE
Update composer.json to require opentok 2.3.x / Issue with ArchiveMode class

### ISSUE THREAD

**Issue by dshaw002** [tomcorbett/opentok-laravel#8]
Latest documentation on OpenTok website references the ArchiveMode class. I put it in and It threw an error in the code. 

I reviewed the latest version of OpenTok on Github and it has the ArchiveMode.php file. This is necessary to enable auto archiving on generated sessions. The version in this extensions composer.json file references 2.2.x version which does not have the file.

**Comment by dshaw002** [comment]
Also OutputMode doesn't work. I don't know if this extension supports archiving.

**Comment by morksinaanab** [comment]
@tomcorbett it seems you are solving this issue in v1.1.1. However packagist is not recognizing v1.1.1 yet. Maybe something went wrong publishing it to packagist?

**Comment by tomcorbett** [comment]
@dshaw002 / @morksinaanab 
All versions updated and published, closing, let me know if still an issue and I will re-open!
